kind: Deployment
apiVersion: apps/v1
metadata:
  name: gaf-server
  namespace: test
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gaf
    app.kubesphere.io/instance: test
    helm.sh/chart: gaf-v3.5.0
  annotations:
    deployment.kubernetes.io/revision: '14'
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: gaf
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/name: gaf
      annotations:
        kubesphere.io/creator: admin
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-ivw9jw
          configMap:
            name: gaf-server-conf
            defaultMode: 420
      containers:
        - name: gaf
          image: 'core.harbor:30002/test/gaf:v3.6.0'
          ports:
            - name: http
              containerPort: 9680
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-ivw9jw
              readOnly: true
              mountPath: /home/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: gaf-server
      serviceAccount: gaf-server
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
